### ISSUE TITLE
Status information about the user is not returned

### ISSUE THREAD

**Issue by dfederschmidt** [freelancer/freelancer-sdk-python#25]
I have troubles obtaining some user information associated with a project with the following query:

```
query = create_get_projects_object(
    project_ids=[
        16590904
    ],
    project_details=create_get_projects_project_details_object(
        attachments=True,
    ),
    user_details=create_get_projects_user_details_object(
        basic=True,
        financial=True,
        responsiveness=True,
        display_info=True,
        balance=True
    ),
)
```
The response has the following `status` field for the employer.

```
   'status': {'deposit_made': None,
    'email_verified': True,
    'facebook_connected': None,
    'identity_verified': None,
    'payment_verified': None,
    'phone_verified': None,
    'profile_complete': None},
```

But when taking a look on the web page, the employer seems to have it's payment verified.

![image](https://user-images.githubusercontent.com/2430239/38111645-d3582c90-339f-11e8-94b6-cb1e8796ff56.png)

Am I missing a parameter for `create_get_projects_user_details_object``or how do I get this field populated with actual values?

**Comment by gabrnavarro** [comment]
@dfederschmidt you are missing the `status` parameter for your `user_details` object. To get the verification statuses, add `status=True` to  your `create_get_projects_user_details_object()` call.

**Comment by dfederschmidt** [comment]
Thank you - that works!
