### ISSUE TITLE
Input attributes goes unrecognized 

### ISSUE THREAD

**Issue by earthat** [freelancer/freelancer-sdk-python#37]
Hi, I am trying to parse the projects with specific key skills after each second and following the search_projects example from the repository. When I tried to pass other search queries except in example, it showed error as
`search_data = {
        'query': 'python',
        'project_types': 'fixed',
        'limit': 100,
        'offset': 0,
      #  'from_time' : 1481179011,
        'countries'  : 'au'
        #'active_only': False,
        #'sort_field' : 'time_updated',
    }`

**Error:**
`TypeError: search_projects() got an unexpected keyword argument 'countries'`

**Comment by gabrnavarro** [comment]
The `search_projects` endpoint in the SDK currently does not support parameters other than `query`, `project_types`, `active_only`, `limit` and `offset`. We will be adding this functionality in future releases.

**Comment by earthat** [comment]
Ok, I am trying to fetch the projects with keywords in every 2 secs and display the notification on my desktop so that I can pay attention to other works. Is there any alternative to `search_projects`

**Comment by gabrnavarro** [comment]
You can do one or more of the following:

- use the `search_projects` endpoint without the additional parameters. 
- use the `get_projects` endpoint along with filters that match your needs 
- access the `search_projects` endpoint using the Freelancer API directly using HTTP calls. 

Take a look at the [Freelancer API Documentation](https://developers.freelancer.com/docs/projects/projects) to know more about the available filters and projections.

**Comment by earthat** [comment]
Thanks, I look into these options

**Comment by earthat** [comment]
While checking with `search_projects` it seems it is not fetching the latest one immediately. I am running the code manually after approx 5 minutes and new projects with 'MATLAB' keywords are posted on site but not fetched in API. Is this something it is limited to.

**Comment by gabrnavarro** [comment]
You may have to use the `sort_field=time_updated` projection, which is currently available through the API.

**Comment by earthat** [comment]
I checked it earlier, `sort_field` is not working

**Comment by gabrnavarro** [comment]
@earthat We are working on adding `sort_field` as well as other projections in the SDK. In the meantime, you can search for projects by using cURL on `/projects/0.1/projects/active/?sort_field=time_updated`.
