### ISSUE TITLE
How to send multiple queries at a time

### ISSUE THREAD

**Issue by earthat** [freelancer/freelancer-sdk-python#38]
Hi, is it any way to fetch the jobs with multiple keywords at a time? For example I am trying to fetch MATLAB and python jobs like 
`para={
    'query':['python','Matlab'],
    #'query':'Matlab',
    'sort_field':'time_updated',
    'limit':10}`
But it only fetches the jobs with last keyword.

**Comment by gabrnavarro** [comment]
@earthat Try using 'query': 'python matlab'.

**Comment by earthat** [comment]
I tried it and also with reverse the sequence, it always notify for MATLAB based jobs, not python jobs. Not working...

**Comment by gabrnavarro** [comment]
@earthat Thanks for letting us know, we're currently working on a fix for this issue.

**Comment by gabrnavarro** [comment]
@earthat Update your SDK to the latest version. It should include the `or_search_query` boolean parameter that searches for the occurrence of each of the terms in the `query` parameter.

Based on your use case, your query should look like this:

```
query = 'python matlab'
    search_filter = create_search_projects_filter(
        sort_field= 'time_updated',
        or_search_query= True,
    )

    try:
        p = search_projects(
            session,
            query=query,
            search_filter=search_filter
        )
```

Have a look at the [updated example](https://github.com/freelancer/freelancer-sdk-python/blob/master/examples/search_projects.py) to see how you can add more options to your query.

**Comment by earthat** [comment]
Thanks a lot @gabrnavarro for update. Will `or_search_query` will work with http requests too. I developed the desktop notification app with it. For your reference it is at 

https://github.com/earthat/freelancing-jobs-desktop-notification

**Comment by gabrnavarro** [comment]
@earthat yes. Adding `or_search_query=True` on your http request should work as well.

**Comment by earthat** [comment]
Thanks, I appreciate your help.

**Comment by earthat** [comment]
Hi again @gabrnavarro , just wondering in case of multiple queries, what will be the sequence of jobs fetched, will it fetch the jobs with first query first and then for the next or will look for the latest. Like I have the limits of 10 jobs, these 10 jobs will be latest of those queries or what?

With Regards

**Comment by gabrnavarro** [comment]
@earthat  If you have the `sort_field= 'time_updated'` parameter in your query, the API will return the latest updated projects in decreasing order(from newest to oldest). You can add `reverse_sort=True` to the `create_search_projects_filter` to return them in increasing order instead. 

The SDK also returns integer timestamps such as `time_updated` and `time_submitted` along with the projects. They can be easily converted to datetime format by using a library such as `datetime`.

```
>>> import datetime
>>> a = 1481179011
>>> date = datetime.datetime.fromtimestamp(1481179011)
>>> print(date)
2016-12-08 14:36:51
```
The [Search projects](https://developers.freelancer.com/docs/projects/projects#projects-get-4) provides the entire list of parameters that you can use for your query.

**Comment by hamzicabdulah** [comment]
Hey, @gabrnavarro 

My question is not really related to the Python SDK, but it is related to Freelancer's API, and I had no idea where to ask this question.

I want to search for Freelancer projects via Freelancer's API with multiple query words. I want the projects to match any one of the words in the query and not all of them. Reading through Freelancer's API and this GitHub issue, I expected sending an HTTP GET request to this URL to work (where either one of the two query words, "web" and "mobile", should be matched):

`/projects/0.1/projects/all?query=web mobile&or_search_query=True`

However, the response I get only includes the projects that match both of these words, as if the or_search_query parameter is not even there. I have also tried switching "True" to lowercase "true", but the same issue remains.

Can you help me with this?
