### ISSUE TITLE
Extract all user information

### ISSUE THREAD

**Issue by earthat** [freelancer/freelancer-sdk-python#40]
Hi

I wonder if it is possible to get the all history of a user like to which jobs he has applied so far in his life time, which is assigned to him, which jobs are assigned to others, which jobs are closed etc.

**Comment by gabrnavarro** [comment]
@earthat you can use the `jobs` projection in the `List Users` use-case in the API. The `jobs` endpoint may also be helpful. Take a look at https://developers.freelancer.com/docs/projects/jobs and https://developers.freelancer.com/docs/users/users for more information. Let me know if you have more questions.
